UI update
doutriaux1/wps_cwt pull request #141
Opened 2018-05-29 21:01 UTC by jasonb5

PR for #118 and #139

2018-05-29 22:45 UTC, doutriaux1 commented on compute/wps/webapp/src/app/configure/regrid.component.ts
> +      methods: ['Conserve', 'Linear']
there's no method for regrid2, just use "area_weighted"

2018-05-29 22:46 UTC, doutriaux1 requested changes
@jasonb5 looks good, just one detail for regrid2 there is no "regrid_method", only one and it is "Area weighted", otherwise all looks ggod.

2018-05-30 00:01 UTC, doutriaux1 approved these changes
make sure it still works 😉 but i think it's ignored by cdms

2018-05-30 00:13 UTC, jasonb5 commented
Yea I checked it, you can pass anything to regridMethod when regridTool is set to "regrid2".

2018-05-30 17:38 UTC, merged